version: "2"
linters:
  disable:
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - lll
    - varnamelen
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
