export PATH := ~/.go/bin:$(PATH)

.PHONY: all generate test update check

all:

generate:
	rec -import=unicode/utf8 -pkg betteralign -matchstringutf8=reGeneratedBy '^//\s*Code generated by .* DO NOT EDIT\.$$' > match_generated.go
	gofumpt -w match_generated.go
	gci write match_generated.go

test:
	go test -v

update:
	go get -u
	go mod tidy

check:
	gomajor list
