// Code generated by [rec -import=unicode/utf8 -pkg betteralign -matchstringutf8=reGeneratedBy ^//\s*Code generated by .* DO NOT EDIT\.$$], DO NOT EDIT.

package betteralign

import (
	"unicode/utf8"
)

// reGeneratedBy matches ^//\s*Code generated by .* DO NOT EDIT\.$$, start condition 4
func reGeneratedBy(s string) bool {
	const endOfText = 0x110000
	const minInputLen = 33
	var pos, pos0, width, width0, width1 int
	var r, r1 rune
	_ = r
	_ = r1
	_ = width1
	lastRestartPos := -1
	step := func(pos int) (r rune, n int) {
		if pos < len(s) {
			c := s[pos]
			if c < utf8.RuneSelf {
				return rune(c), 1
			}
			return utf8.DecodeRuneInString(s[pos:])
		}
		return endOfText, 0
	}
restart:
	r, r1 = endOfText, endOfText
	width, width1 = 0, 0
	r, width = step(pos)
	if r != endOfText {
		r1, width1 = step(pos + width)
	}
	if pos == lastRestartPos {
		return false
	}
	lastRestartPos = pos
	if pos != 0 {
		return false
	}
	pos0 = pos
	width0 = width

	if pos != pos0 {
		return false
	}
	goto l3

	pos = pos0 + width0
	goto restart
l3:
	if r == '/' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l6
	}

	pos = pos0 + width0
	goto restart
l6:
	if r == '/' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l9
	}

	pos = pos0 + width0
	goto restart
l9:
	if r == '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == '\n' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == '\f' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == '\r' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == 'C' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l35
	}

	pos = pos0 + width0
	goto restart
l22:
	if r == '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == '\n' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == '\f' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == '\r' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l22
	}

	if r == 'C' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l35
	}

	pos = pos0 + width0
	goto restart
l35:
	if r == 'o' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l38
	}

	pos = pos0 + width0
	goto restart
l38:
	if r == 'd' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l41
	}

	pos = pos0 + width0
	goto restart
l41:
	if r == 'e' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l44
	}

	pos = pos0 + width0
	goto restart
l44:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l47
	}

	pos = pos0 + width0
	goto restart
l47:
	if r == 'g' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l50
	}

	pos = pos0 + width0
	goto restart
l50:
	if r == 'e' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l53
	}

	pos = pos0 + width0
	goto restart
l53:
	if r == 'n' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l56
	}

	pos = pos0 + width0
	goto restart
l56:
	if r == 'e' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l59
	}

	pos = pos0 + width0
	goto restart
l59:
	if r == 'r' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l62
	}

	pos = pos0 + width0
	goto restart
l62:
	if r == 'a' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l65
	}

	pos = pos0 + width0
	goto restart
l65:
	if r == 't' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l68
	}

	pos = pos0 + width0
	goto restart
l68:
	if r == 'e' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l71
	}

	pos = pos0 + width0
	goto restart
l71:
	if r == 'd' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l74
	}

	pos = pos0 + width0
	goto restart
l74:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l77
	}

	pos = pos0 + width0
	goto restart
l77:
	if r == 'b' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l80
	}

	pos = pos0 + width0
	goto restart
l80:
	if r == 'y' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l83
	}

	pos = pos0 + width0
	goto restart
l83:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l86
	}

	pos = pos0 + width0
	goto restart
l86:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r < '\x00' {
		goto l88out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l88out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l88out:
	;
	pos = pos0 + width0
	goto restart
l91:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == 'D' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l98
	}

	if r < '\x00' {
		goto l95out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l95out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l95out:
	;
	pos = pos0 + width0
	goto restart
l98:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == 'O' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l105
	}

	if r < '\x00' {
		goto l102out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l102out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l102out:
	;
	pos = pos0 + width0
	goto restart
l105:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l110
	}

	if r < '\x00' {
		goto l107out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l107out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l107out:
	;
	pos = pos0 + width0
	goto restart
l110:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == 'D' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l98
	}

	if r == 'N' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l119
	}

	if r < '\x00' {
		goto l116out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l116out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l116out:
	;
	pos = pos0 + width0
	goto restart
l119:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == 'O' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l126
	}

	if r < '\x00' {
		goto l123out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l123out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l123out:
	;
	pos = pos0 + width0
	goto restart
l126:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == 'T' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l133
	}

	if r < '\x00' {
		goto l130out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l130out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l130out:
	;
	pos = pos0 + width0
	goto restart
l133:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l138
	}

	if r < '\x00' {
		goto l135out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l135out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l135out:
	;
	pos = pos0 + width0
	goto restart
l138:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == 'D' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l98
	}

	if r == 'E' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l147
	}

	if r < '\x00' {
		goto l144out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l144out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l144out:
	;
	pos = pos0 + width0
	goto restart
l147:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == 'D' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l154
	}

	if r < '\x00' {
		goto l151out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l151out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l151out:
	;
	pos = pos0 + width0
	goto restart
l154:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == 'I' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l161
	}

	if r < '\x00' {
		goto l158out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l158out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l158out:
	;
	pos = pos0 + width0
	goto restart
l161:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == 'T' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l168
	}

	if r < '\x00' {
		goto l165out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l165out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l165out:
	;
	pos = pos0 + width0
	goto restart
l168:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r == '.' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l175
	}

	if r < '\x00' {
		goto l172out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l172out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l172out:
	;
	pos = pos0 + width0
	goto restart
l175:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r < '\x00' {
		goto l177out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l177out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l177out:
	;
	if r == endOfText {
		goto l187
	}

	pos = pos0 + width0
	goto restart
l182:
	if r == ' ' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l91
	}

	if r < '\x00' {
		goto l184out
	}
	if r <= '\t' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
	if r < '\v' {
		goto l184out
	}
	if r <= '\U0010ffff' {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
		goto l182
	}
l184out:
	;
	pos = pos0 + width0
	goto restart
l187:
	if r == endOfText {
		return true
	}

	pos = pos0 + width0
	goto restart

	return true

	pos = pos0 + width0
	goto restart
}
