// Code generated by tool. DO NOT EDIT.

// `aaa.go` sorts before `bbb.go`; this file's skip must not leak into the next.

package skipcarry

type SkipCarryGenerated struct {
	x byte
	y int32
	z byte
}
